apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sentinance

resources:
  - prometheus.yaml
  - grafana.yaml
  - grafana-dashboard.yaml

commonLabels:
  app.kubernetes.io/part-of: sentinance-monitoring
